# Generated by Django 5.0.6 on 2024-06-28 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Repairs', 'Repairs'), ('Inspections', 'Inspections'), ('Installations', 'Installations'), ('Custom', 'Custom')], default='Maintenance', max_length=100)),
                ('type', models.CharField(choices=[('Oil Change', 'Oil Change (60 minutes)'), ('Tire Rotation', 'Tire Rotation (45 minutes)'), ('Brake Inspection', 'Brake Inspection (90 minutes)'), ('Engine Repair', 'Engine Repair (180 minutes)'), ('Transmission Repair', 'Transmission Repair (240 minutes)'), ('Safety Inspection', 'Safety Inspection (60 minutes)'), ('Emissions Inspection', 'Emissions Inspection (45 minutes)'), ('Audio System Installation', 'Audio System Installation (120 minutes)'), ('Window Tinting', 'Window Tinting (90 minutes)'), ('Custom', 'Custom (specify service details in description box!)')], default='Oil Change', max_length=100)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes for custom service', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20)),
                ('appointment_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, help_text='Enter service details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='car_services.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='car_services.vehicle')),
            ],
        ),
    ]
